//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHelperClass.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestHelperClass.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Add Employee.
        /// </summary>
        internal static string ADD_EMPLOYEE_EN_ERROR {
            get {
                return ResourceManager.GetString("ADD_EMPLOYEE_EN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل فى ادخال الموظف.
        /// </summary>
        internal static string ADD_EMPLOYEE_ERROR {
            get {
                return ResourceManager.GetString("ADD_EMPLOYEE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال عنوان صحيح وباللغة العربية.
        /// </summary>
        internal static string ADRESS_AR_ERROR {
            get {
                return ResourceManager.GetString("ADRESS_AR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address You Enter Is In Correct, Please Enter a Valid Address.
        /// </summary>
        internal static string ADRESS_EN_ERROR {
            get {
                return ResourceManager.GetString("ADRESS_EN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم أرشفت هذا الموظف من قبل.
        /// </summary>
        internal static string ARCHIVE_DB_ERROR {
            get {
                return ResourceManager.GetString("ARCHIVE_DB_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This employee already archived.
        /// </summary>
        internal static string ARCHIVE_EN_DB_ERROR {
            get {
                return ResourceManager.GetString("ARCHIVE_EN_DB_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Correct Name Or Correct Phone Number.
        /// </summary>
        internal static string CORRECT_EN_NAME_AND_PHONE {
            get {
                return ResourceManager.GetString("CORRECT_EN_NAME_AND_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال اسم موظف صحيح وباللغة العربية او رقم هاتف.
        /// </summary>
        internal static string CORRECT_NAME_AND_PHONE {
            get {
                return ResourceManager.GetString("CORRECT_NAME_AND_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Delete.
        /// </summary>
        internal static string DELETE_EN_ERROR {
            get {
                return ResourceManager.GetString("DELETE_EN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل فى حذف الموظف.
        /// </summary>
        internal static string DELETE_ERROR {
            get {
                return ResourceManager.GetString("DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه البيانات موجود مسبقا.
        /// </summary>
        internal static string DOUBLE_DATA_ERROR {
            get {
                return ResourceManager.GetString("DOUBLE_DATA_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجد ادخال بيانات صحيحه.
        /// </summary>
        internal static string EMPLOYEE_NULL_ERROR {
            get {
                return ResourceManager.GetString("EMPLOYEE_NULL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EMPTY {
            get {
                return ResourceManager.GetString("EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الموظف غير موجود.
        /// </summary>
        internal static string EMPTY_EMPLOYEE_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_EMPLOYEE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Employee Is Not Existed.
        /// </summary>
        internal static string EMPTY_EN_EMPLOYEE_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_EN_EMPLOYEE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل فى الوصول لقاعدة البيانات.
        /// </summary>
        internal static string FAILED_DB_CONNECTION {
            get {
                return ResourceManager.GetString("FAILED_DB_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Return All Employee.
        /// </summary>
        internal static string GETALL_EMPLOYEE_EN_ERROR {
            get {
                return ResourceManager.GetString("GETALL_EMPLOYEE_EN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل فى ارجاع جميع الموظفين.
        /// </summary>
        internal static string GETALL_EMPLOYEE_ERROR {
            get {
                return ResourceManager.GetString("GETALL_EMPLOYEE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال لغة صحيحة.
        /// </summary>
        internal static string LANG_ERROR {
            get {
                return ResourceManager.GetString("LANG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال جميع البيانات المطلوبة.
        /// </summary>
        internal static string LIST_ERROR {
            get {
                return ResourceManager.GetString("LIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال اسم صحيح وباللغة العربية.
        /// </summary>
        internal static string NAME_AR_ERROR {
            get {
                return ResourceManager.GetString("NAME_AR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name You Enter Is In Correct, Please Enter a Valid Name.
        /// </summary>
        internal static string NAME_EN_ERROR {
            get {
                return ResourceManager.GetString("NAME_EN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name Is Existed Before.
        /// </summary>
        internal static string NAME_EN_IS_EXIST {
            get {
                return ResourceManager.GetString("NAME_EN_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الاسم موجود مسبقا.
        /// </summary>
        internal static string NAME_IS_EXIST {
            get {
                return ResourceManager.GetString("NAME_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name Not Existed.
        /// </summary>
        internal static string NAME_NOT_EN_EXIST {
            get {
                return ResourceManager.GetString("NAME_NOT_EN_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الموظف غير موجود.
        /// </summary>
        internal static string NAME_NOT_EXIST {
            get {
                return ResourceManager.GetString("NAME_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء اخال رقم هاتف صحيح.
        /// </summary>
        internal static string PHONE_AR_ERROR {
            get {
                return ResourceManager.GetString("PHONE_AR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone Number You Enter Is In Correcr, Please Enter a Valid Phone Number.
        /// </summary>
        internal static string PHONE_EN_ERROR {
            get {
                return ResourceManager.GetString("PHONE_EN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone Number Is Existed Before.
        /// </summary>
        internal static string PHONE_EN_IS_EXIST {
            get {
                return ResourceManager.GetString("PHONE_EN_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Not Existed.
        /// </summary>
        internal static string PHONE_EN_NOT_EXIST {
            get {
                return ResourceManager.GetString("PHONE_EN_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الرقم موجود مسبقا.
        /// </summary>
        internal static string PHONE_IS_EXIST {
            get {
                return ResourceManager.GetString("PHONE_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم تليفون الموظف غير موجود.
        /// </summary>
        internal static string PHONE_NOT_EXIST {
            get {
                return ResourceManager.GetString("PHONE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This employee is not archived.
        /// </summary>
        internal static string RESTORE_EN_ERROR {
            get {
                return ResourceManager.GetString("RESTORE_EN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الموظف غير مأرشف .
        /// </summary>
        internal static string RESTORE_ERROR {
            get {
                return ResourceManager.GetString("RESTORE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeded Operation.
        /// </summary>
        internal static string SUCCEDED_EN_MESSAGES {
            get {
                return ResourceManager.GetString("SUCCEDED_EN_MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملية ناجحة.
        /// </summary>
        internal static string SUCCEDED_MESSAGES {
            get {
                return ResourceManager.GetString("SUCCEDED_MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Update.
        /// </summary>
        internal static string UPDATED_EN_FAILED {
            get {
                return ResourceManager.GetString("UPDATED_EN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل فى تحديث بيانات الموظف.
        /// </summary>
        internal static string UPDATED_FAILED {
            get {
                return ResourceManager.GetString("UPDATED_FAILED", resourceCulture);
            }
        }
    }
}
